# Generated by Django 4.1 on 2022-10-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="churidar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Camp_id", models.CharField(max_length=35)),
                ("Camp_Name", models.IntegerField()),
                ("Name", models.CharField(max_length=540)),
                ("Mailid", models.CharField(max_length=140)),
                ("Password", models.CharField(max_length=100)),
                ("Camp_address", models.CharField(max_length=300)),
                ("District", models.CharField(max_length=100)),
                ("State", models.CharField(max_length=140)),
                ("Country", models.CharField(max_length=140)),
                ("Pincode", models.IntegerField()),
                ("img", models.ImageField(upload_to="pics")),
                ("Total_noof_capacity", models.CharField(max_length=140)),
            ],
        ),
    ]
