# Generated by Django 4.1 on 2022-10-01 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flood", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="churidar", new_name="flood",),
    ]
