# Generated by Django 4.1 on 2022-10-01 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flood", "0002_rename_churidar_flood"),
    ]

    operations = [
        migrations.RenameModel(old_name="flood", new_name="floods",),
    ]
