# Generated by Django 4.1 on 2022-10-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flood", "0004_alter_floods_camp_name_alter_floods_camp_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=36)),
                ("Age", models.IntegerField()),
                ("Gender", models.CharField(max_length=32)),
                ("Address", models.CharField(max_length=45)),
                ("Contact", models.IntegerField()),
            ],
        ),
    ]
