# Generated by Django 4.1 on 2022-10-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flood", "0005_form"),
    ]

    operations = [
        migrations.CreateModel(
            name="regist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Camp_Id", models.IntegerField()),
                ("Product", models.CharField(max_length=32)),
                ("Quanty", models.CharField(max_length=32)),
            ],
        ),
    ]
