# Generated by Django 4.1 on 2022-10-02 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flood", "0007_form_camp_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="form", name="Camp_ID",),
    ]
