# Generated by Django 4.1 on 2022-10-02 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flood", "0009_form_camp_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="form", old_name="Camp_ID", new_name="Camp_Id",
        ),
        migrations.RenameField(
            model_name="regist", old_name="Quanty", new_name="Quantity",
        ),
    ]
