# Generated by Django 4.1 on 2022-10-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flood", "0010_rename_camp_id_form_camp_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="floods", name="Camp_id", field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name="form", name="Camp_Id", field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name="regist", name="Camp_Id", field=models.CharField(max_length=6),
        ),
    ]
